###
GET http://localhost:8080/authors

###
POST http://localhost:8080/authors

{
  id: 5
}

###
GET http://localhost:8080/authors/1

###
PUT http://localhost:8080/authors/5

{
  name: "dsa"
}

###
DELETE http://localhost:8080/authors/1