###
GET http://localhost:8080/books

###
POST http://localhost:8080/books

{
  id: 5
}

###
GET http://localhost:8080/books/1

###
PUT http://localhost:8080/books/5

{
  name: "dsa"
}

###
DELETE http://localhost:8080/books/5