###
GET http://localhost:8080/customers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.gaYjFmySJtByvhzHbfd_HI0u1T-U-JyPvp-wz--7XZY

###
POST http://localhost:8080/customers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGVtYWlsLmNvbSIsImV4cCI6MTY5Nzg5ODQwNn0.CrzabcO2Gs3-wXg_L6EJmH28n0DyUuB9uqLwJNFJt7M
content-type: application/json

{
			"firstName": "John",
			"lastName": "Doe",
			"address": "123 Main St",
		  "phoneNumber": "555-123-4567",
			"email": "john.doe@email.com",
			"lateDeliveryScore": 5,
}

###
GET http://localhost:8080/customers/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGVtYWlsLmNvbSIsImV4cCI6MTY5Nzg5ODQwNn0.CrzabcO2Gs3-wXg_L6EJmH28n0DyUuB9uqLwJNFJt7M

###
PUT http://localhost:8080/customers/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGVtYWlsLmNvbSIsImV4cCI6MTY5Nzg5ODQwNn0.CrzabcO2Gs3-wXg_L6EJmH28n0DyUuB9uqLwJNFJt7M

{
  name: "dsa"
}

###
DELETE http://localhost:8080/customers/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGVtYWlsLmNvbSIsImV4cCI6MTY5Nzg5ODQwNn0.CrzabcO2Gs3-wXg_L6EJmH28n0DyUuB9uqLwJNFJt7M