###
GET http://localhost:8080/customers

###
POST http://localhost:8080/customers

{
  id: 5
}

###
GET http://localhost:8080/customers/1

###
PUT http://localhost:8080/customers/5

{
  name: "dsa"
}

###
DELETE http://localhost:8080/customers/5