###
GET http://localhost:8080/loans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM

###
POST http://localhost:8080/loans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM

{
  id: 5
}

###
GET http://localhost:8080/loans/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM

###
PUT http://localhost:8080/loans/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM

{
  name: "dsa"
}

###
DELETE http://localhost:8080/loans/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM