###
GET http://localhost:8080/loans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxNDI1NzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZX19.4MGzzYBgGrcFEL-YIJEjLfzFJsT-fXYK3FH_8ml59F4

###
POST http://localhost:8080/loans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxNDI1NzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZX19.4MGzzYBgGrcFEL-YIJEjLfzFJsT-fXYK3FH_8ml59F4

{
  id: 5
}

###
GET http://localhost:8080/loans/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxNDI1NzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZX19.4MGzzYBgGrcFEL-YIJEjLfzFJsT-fXYK3FH_8ml59F4

###
PUT http://localhost:8080/loans/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxNDI1NzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZX19.4MGzzYBgGrcFEL-YIJEjLfzFJsT-fXYK3FH_8ml59F4

{
  name: "dsa"
}

###
DELETE http://localhost:8080/loans/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxNDI1NzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZX19.4MGzzYBgGrcFEL-YIJEjLfzFJsT-fXYK3FH_8ml59F4