POST http://localhost:8080/login
Content-Type: "application/json"

{
  "email": "john.doe@email.com",
  "password": "myadminpassword"
}

###

POST http://localhost:8080/login
Content-Type: "application/json"

{
  "email": "jane.smith@email.com",
  "password": "mypassword"
}