###
GET http://localhost:8080/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.gaYjFmySJtByvhzHbfd_HI0u1T-U-JyPvp-wz--7XZY

###
POST http://localhost:8080/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM
content-type: application/json

{
			"firstName": "John",
			"lastName": "Doe",
			"address": "123 Main St",
		  "phoneNumber": "555-123-4567",
			"email": "john.doe@email.com",
			"lateDeliveryScore": 5,
}

###
GET http://localhost:8080/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM

###
PUT http://localhost:8080/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM

{
  name: "dsa"
}

###
DELETE http://localhost:8080/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMzM5MzEsInVzZXIiOnsiVXNlcklEIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJhZGRyZXNzIjoiMTIzIE1haW4gU3QiLCJwaG9uZSI6IjU1NS0xMjMtNDU2NyIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2V9fQ.kOGgHwAIojs0wiqR0k6xxgewagZXVSkv_l2DAf-jalM